//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeCompare.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IVerifier")]
    public interface IVerifier {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerifier/HelloWord", ReplyAction="http://tempuri.org/IVerifier/HelloWordResponse")]
        string HelloWord();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerifier/HelloWord", ReplyAction="http://tempuri.org/IVerifier/HelloWordResponse")]
        System.Threading.Tasks.Task<string> HelloWordAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerifier/CallInterface", ReplyAction="http://tempuri.org/IVerifier/CallInterfaceResponse")]
        string CallInterface(string InterfaceNo, string Params, string AttachParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerifier/CallInterface", ReplyAction="http://tempuri.org/IVerifier/CallInterfaceResponse")]
        System.Threading.Tasks.Task<string> CallInterfaceAsync(string InterfaceNo, string Params, string AttachParams);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVerifierChannel : BarcodeCompare.ServiceReference1.IVerifier, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VerifierClient : System.ServiceModel.ClientBase<BarcodeCompare.ServiceReference1.IVerifier>, BarcodeCompare.ServiceReference1.IVerifier {
        
        public VerifierClient() {
        }
        
        public VerifierClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VerifierClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VerifierClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VerifierClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWord() {
            return base.Channel.HelloWord();
        }
        
        public System.Threading.Tasks.Task<string> HelloWordAsync() {
            return base.Channel.HelloWordAsync();
        }
        
        public string CallInterface(string InterfaceNo, string Params, string AttachParams) {
            return base.Channel.CallInterface(InterfaceNo, Params, AttachParams);
        }
        
        public System.Threading.Tasks.Task<string> CallInterfaceAsync(string InterfaceNo, string Params, string AttachParams) {
            return base.Channel.CallInterfaceAsync(InterfaceNo, Params, AttachParams);
        }
    }
}
